[package]
name = "errors"
version = "0.1.0"
authors = ["Niranjana <niranjana687>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[profile.release]
panice = 'abort'
[dependencies]
